version: '3'
services:
  iris:
    build: .
    ports: 
      - 1972
      - 19092:52773
    command: 
      - -a
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
    volumes: 
      - .:/home/irisowner/saml-example/
